### ISSUE TITLE
Does this wipe the apps/data that are on the phone already?

### ISSUE THREAD

**Issue by Ma-XX-oN** [Raymo111/oneplus-7t-root#3]
I want to backup my phone and I've been postponing it too long.  I used Titanium a while ago and did like it but it requires root (as do many other backup apps).  So if I root using this method, will I lose all of the information that is on the phone currently.  Yeah, I know it should be backed up before this, but *shrug*.

**Comment by Raymo111** [comment]
It shouldn't.
