### ISSUE TITLE
Question with your instructions

### ISSUE THREAD

**Issue by Ma-XX-oN** [Raymo111/oneplus-7t-root#5]
> - I've confirmed that major OOS updates (like 10->11) DO work with the update method below (keep root without losing data). However, it is still your responsibility to backup your data!

What does this mean exactly?  That root is maintained when doing an OTA update?  Or that I can have 11 installed already and use this method to root my phone, even though this is a version 10 rom?

The Build number I have is 11.0.3.0.HD65AA. The Model is HD1900.

**Comment by Raymo111** [comment]
It means that when you do an OTA update, even for major version upgrades, root will be kept.
